name: Deploy to vercel

on:
  push:
    branches: [main]

jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel redundant workflows
        uses: technote-space/auto-cancel-redundant-workflow@v1

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install vercel
        run: npm i vercel -g

      - name: Deploy landing page
        run: cd examples/solana-wallet-adapter && ls && vercel --token $VERCEL_TOKEN --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
